#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tipsy-turtle','console_scripts','main'
__requires__ = 'tipsy-turtle'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tipsy-turtle', 'console_scripts', 'main')()
    )
